"""M9 draft: user ranking boards and saved mock drafts

Four user-owned tables: a user's own ranking boards (uploaded or built in the editor)
and the mock drafts they finished.

⚠️ **All four are RLS-locked and revoked at the end of this migration**, by the same
two-layer fix as `8f73b5b2b1a1`: Supabase serves the whole `public` schema through
PostgREST and grants the public `anon` key access to new tables there, so a user-data
table created by a plain Alembic migration is world-readable *and writable*, bypassing
the API entirely. The backend connects as the table owner and bypasses RLS, so this
costs nothing. **No policies are created** — a policy is the first step toward the
browser talking to the database directly, which this architecture rejects.

Global ranking sources are deliberately **not** here: FantasyPros ECR and the dropped
expert boards live in `player_rankings` (M6.1), which was multi-source from day one.

See docs/design/M9-draft.md §4.3 and §4.4.

Revision ID: 0fd5c30c9287
Revises: 69b660509e58
Create Date: 2026-08-23 17:24:12.646290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fd5c30c9287'
down_revision: Union[str, None] = '69b660509e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# The user-data tables this migration adds. Everything else in `public` is locked by
# 69b660509e58 — no table in this schema is exempt.
DRAFT_TABLES = (
    "ranking_boards",
    "ranking_board_entries",
    "mock_drafts",
    "mock_draft_picks",
)

# Roles PostgREST connects as on Supabase. They do not exist on a plain local
# Postgres, so every revoke is guarded — this migration must run identically against
# local Docker, the test harness, and Supabase.
EXPOSED_ROLES = ("anon", "authenticated")


def _for_role_if_exists(role: str, statement: str) -> str:
    """Wrap a grant/revoke so it is skipped where the role does not exist."""
    return f"""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{role}') THEN
                {statement};
            END IF;
        END
        $$;
    """


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_drafts',
    sa.Column('mock_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scoring_spec', sa.String(length=500), nullable=False),
    sa.Column('league_spec', sa.String(length=200), nullable=False),
    sa.Column('teams', sa.Integer(), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('draft_slot', sa.Integer(), nullable=False),
    sa.Column('bot_source', sa.String(length=60), nullable=False),
    sa.Column('bot_randomness', sa.Float(), nullable=False),
    sa.Column('grade_vorp', sa.Float(), nullable=True),
    sa.Column('grade_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mock_id')
    )
    op.create_index(op.f('ix_mock_drafts_user_id'), 'mock_drafts', ['user_id'], unique=False)
    op.create_table('ranking_boards',
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('ranking_type', sa.String(length=40), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('seeded_from', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('board_id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_board_user_name')
    )
    op.create_index(op.f('ix_ranking_boards_user_id'), 'ranking_boards', ['user_id'], unique=False)
    op.create_table('mock_draft_picks',
    sa.Column('mock_id', sa.UUID(), nullable=False),
    sa.Column('pick_number', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('team_slot', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=50), nullable=False),
    sa.Column('is_user', sa.Boolean(), nullable=False),
    sa.Column('auto', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['mock_id'], ['mock_drafts.mock_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mock_id', 'pick_number')
    )
    op.create_table('ranking_board_entries',
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.String(length=50), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['ranking_boards.board_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('board_id', 'player_id')
    )
    op.create_index('ix_board_entries_rank', 'ranking_board_entries', ['board_id', 'rank'], unique=False)
    # ### end Alembic commands ###

    # Lock the new user-data tables away from PostgREST — see the module docstring.
    for table in DRAFT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        for role in EXPOSED_ROLES:
            op.execute(_for_role_if_exists(role, f"REVOKE ALL ON TABLE {table} FROM {role}"))


def downgrade() -> None:
    # Dropping the tables takes their RLS with them; the grants are restored first
    # only so the revision is a faithful inverse.
    for table in DRAFT_TABLES:
        for role in EXPOSED_ROLES:
            op.execute(_for_role_if_exists(role, f"GRANT ALL ON TABLE {table} TO {role}"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_board_entries_rank', table_name='ranking_board_entries')
    op.drop_table('ranking_board_entries')
    op.drop_table('mock_draft_picks')
    op.drop_index(op.f('ix_ranking_boards_user_id'), table_name='ranking_boards')
    op.drop_table('ranking_boards')
    op.drop_index(op.f('ix_mock_drafts_user_id'), table_name='mock_drafts')
    op.drop_table('mock_drafts')
    # ### end Alembic commands ###
