"""Team pages: team_game_stats, team_personnel, team_staff, teams.color

Three tables for the team pages and team leaderboards, and the team colour that tints
a team page's header. Every new table is RLS-locked in the same migration that creates
it (CLAUDE.md: a table in `public` without RLS is readable and writable by the anon
key), and `anon` / `authenticated` lose their default grants on it.

Revision ID: 177a7137df5c
Revises: 1dbc965aa956
Create Date: 2026-09-26 20:06:55.639701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '177a7137df5c'
down_revision: Union[str, None] = '1dbc965aa956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


NEW_TABLES = ("team_game_stats", "team_personnel", "team_staff")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_staff',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('head_coach', sa.JSON(), nullable=True),
    sa.Column('offensive_coordinator', sa.JSON(), nullable=True),
    sa.Column('defensive_coordinator', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('team_id', 'season')
    )
    op.create_table('team_game_stats',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('side', sa.String(length=1), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('season_type', sa.String(length=20), nullable=True),
    sa.Column('plays', sa.Float(), nullable=True),
    sa.Column('dropbacks', sa.Float(), nullable=True),
    sa.Column('designed_runs', sa.Float(), nullable=True),
    sa.Column('epa', sa.Float(), nullable=True),
    sa.Column('successes', sa.Float(), nullable=True),
    sa.Column('dropback_epa', sa.Float(), nullable=True),
    sa.Column('dropback_successes', sa.Float(), nullable=True),
    sa.Column('run_epa', sa.Float(), nullable=True),
    sa.Column('run_successes', sa.Float(), nullable=True),
    sa.Column('yards', sa.Float(), nullable=True),
    sa.Column('explosive_passes', sa.Float(), nullable=True),
    sa.Column('explosive_runs', sa.Float(), nullable=True),
    sa.Column('pass_attempts', sa.Float(), nullable=True),
    sa.Column('completions', sa.Float(), nullable=True),
    sa.Column('passing_yards', sa.Float(), nullable=True),
    sa.Column('passing_tds', sa.Float(), nullable=True),
    sa.Column('interceptions', sa.Float(), nullable=True),
    sa.Column('sacks', sa.Float(), nullable=True),
    sa.Column('cpoe_sum', sa.Float(), nullable=True),
    sa.Column('cpoe_attempts', sa.Float(), nullable=True),
    sa.Column('air_yards_sum', sa.Float(), nullable=True),
    sa.Column('air_yards_attempts', sa.Float(), nullable=True),
    sa.Column('yac_sum', sa.Float(), nullable=True),
    sa.Column('yac_completions', sa.Float(), nullable=True),
    sa.Column('rushing_yards', sa.Float(), nullable=True),
    sa.Column('rushing_tds', sa.Float(), nullable=True),
    sa.Column('stuffs', sa.Float(), nullable=True),
    sa.Column('first_downs', sa.Float(), nullable=True),
    sa.Column('neutral_plays', sa.Float(), nullable=True),
    sa.Column('neutral_dropbacks', sa.Float(), nullable=True),
    sa.Column('neutral_pass_oe_sum', sa.Float(), nullable=True),
    sa.Column('neutral_pass_oe_plays', sa.Float(), nullable=True),
    sa.Column('neutral_seconds_sum', sa.Float(), nullable=True),
    sa.Column('neutral_seconds_snaps', sa.Float(), nullable=True),
    sa.Column('third_down_conversions', sa.Float(), nullable=True),
    sa.Column('third_down_attempts', sa.Float(), nullable=True),
    sa.Column('fourth_down_conversions', sa.Float(), nullable=True),
    sa.Column('fourth_down_attempts', sa.Float(), nullable=True),
    sa.Column('fourth_down_decisions', sa.Float(), nullable=True),
    sa.Column('fourth_down_goes', sa.Float(), nullable=True),
    sa.Column('drives', sa.Float(), nullable=True),
    sa.Column('drive_points', sa.Float(), nullable=True),
    sa.Column('red_zone_trips', sa.Float(), nullable=True),
    sa.Column('red_zone_tds', sa.Float(), nullable=True),
    sa.Column('three_and_outs', sa.Float(), nullable=True),
    sa.Column('turnover_drives', sa.Float(), nullable=True),
    sa.Column('start_yardline_sum', sa.Float(), nullable=True),
    sa.Column('start_yardline_drives', sa.Float(), nullable=True),
    sa.Column('snaps', sa.Float(), nullable=True),
    sa.Column('penalties', sa.Float(), nullable=True),
    sa.Column('penalty_yards', sa.Float(), nullable=True),
    sa.Column('giveaways', sa.Float(), nullable=True),
    sa.Column('takeaways', sa.Float(), nullable=True),
    sa.Column('ftn_plays', sa.Float(), nullable=True),
    sa.Column('shotgun_plays', sa.Float(), nullable=True),
    sa.Column('under_center_plays', sa.Float(), nullable=True),
    sa.Column('motion_plays', sa.Float(), nullable=True),
    sa.Column('no_huddle_plays', sa.Float(), nullable=True),
    sa.Column('empty_plays', sa.Float(), nullable=True),
    sa.Column('rpo_plays', sa.Float(), nullable=True),
    sa.Column('ftn_dropbacks', sa.Float(), nullable=True),
    sa.Column('play_action_dropbacks', sa.Float(), nullable=True),
    sa.Column('screen_dropbacks', sa.Float(), nullable=True),
    sa.Column('blitzed_dropbacks', sa.Float(), nullable=True),
    sa.Column('pass_rushers_sum', sa.Float(), nullable=True),
    sa.Column('pass_rushers_dropbacks', sa.Float(), nullable=True),
    sa.Column('ftn_designed_runs', sa.Float(), nullable=True),
    sa.Column('stacked_box_runs', sa.Float(), nullable=True),
    sa.Column('ftn_attempts', sa.Float(), nullable=True),
    sa.Column('throwaways', sa.Float(), nullable=True),
    sa.Column('catchable_throws', sa.Float(), nullable=True),
    sa.Column('drops', sa.Float(), nullable=True),
    sa.Column('interception_worthy', sa.Float(), nullable=True),
    sa.Column('coverage_dropbacks', sa.Float(), nullable=True),
    sa.Column('man_dropbacks', sa.Float(), nullable=True),
    sa.Column('depth_behind_attempts', sa.Float(), nullable=True),
    sa.Column('depth_behind_epa', sa.Float(), nullable=True),
    sa.Column('depth_behind_successes', sa.Float(), nullable=True),
    sa.Column('depth_behind_completions', sa.Float(), nullable=True),
    sa.Column('depth_behind_yards', sa.Float(), nullable=True),
    sa.Column('depth_short_attempts', sa.Float(), nullable=True),
    sa.Column('depth_short_epa', sa.Float(), nullable=True),
    sa.Column('depth_short_successes', sa.Float(), nullable=True),
    sa.Column('depth_short_completions', sa.Float(), nullable=True),
    sa.Column('depth_short_yards', sa.Float(), nullable=True),
    sa.Column('depth_intermediate_attempts', sa.Float(), nullable=True),
    sa.Column('depth_intermediate_epa', sa.Float(), nullable=True),
    sa.Column('depth_intermediate_successes', sa.Float(), nullable=True),
    sa.Column('depth_intermediate_completions', sa.Float(), nullable=True),
    sa.Column('depth_intermediate_yards', sa.Float(), nullable=True),
    sa.Column('depth_deep_attempts', sa.Float(), nullable=True),
    sa.Column('depth_deep_epa', sa.Float(), nullable=True),
    sa.Column('depth_deep_successes', sa.Float(), nullable=True),
    sa.Column('depth_deep_completions', sa.Float(), nullable=True),
    sa.Column('depth_deep_yards', sa.Float(), nullable=True),
    sa.Column('lane_left_end_runs', sa.Float(), nullable=True),
    sa.Column('lane_left_end_epa', sa.Float(), nullable=True),
    sa.Column('lane_left_end_successes', sa.Float(), nullable=True),
    sa.Column('lane_left_end_yards', sa.Float(), nullable=True),
    sa.Column('lane_left_tackle_runs', sa.Float(), nullable=True),
    sa.Column('lane_left_tackle_epa', sa.Float(), nullable=True),
    sa.Column('lane_left_tackle_successes', sa.Float(), nullable=True),
    sa.Column('lane_left_tackle_yards', sa.Float(), nullable=True),
    sa.Column('lane_left_guard_runs', sa.Float(), nullable=True),
    sa.Column('lane_left_guard_epa', sa.Float(), nullable=True),
    sa.Column('lane_left_guard_successes', sa.Float(), nullable=True),
    sa.Column('lane_left_guard_yards', sa.Float(), nullable=True),
    sa.Column('lane_middle_runs', sa.Float(), nullable=True),
    sa.Column('lane_middle_epa', sa.Float(), nullable=True),
    sa.Column('lane_middle_successes', sa.Float(), nullable=True),
    sa.Column('lane_middle_yards', sa.Float(), nullable=True),
    sa.Column('lane_right_guard_runs', sa.Float(), nullable=True),
    sa.Column('lane_right_guard_epa', sa.Float(), nullable=True),
    sa.Column('lane_right_guard_successes', sa.Float(), nullable=True),
    sa.Column('lane_right_guard_yards', sa.Float(), nullable=True),
    sa.Column('lane_right_tackle_runs', sa.Float(), nullable=True),
    sa.Column('lane_right_tackle_epa', sa.Float(), nullable=True),
    sa.Column('lane_right_tackle_successes', sa.Float(), nullable=True),
    sa.Column('lane_right_tackle_yards', sa.Float(), nullable=True),
    sa.Column('lane_right_end_runs', sa.Float(), nullable=True),
    sa.Column('lane_right_end_epa', sa.Float(), nullable=True),
    sa.Column('lane_right_end_successes', sa.Float(), nullable=True),
    sa.Column('lane_right_end_yards', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['opponent_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('team_id', 'game_id', 'side')
    )
    op.create_index('ix_team_game_stats_season', 'team_game_stats', ['season', 'season_type'], unique=False)
    op.create_table('team_personnel',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('grouping', sa.String(length=4), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('season_type', sa.String(length=20), nullable=True),
    sa.Column('plays', sa.Float(), nullable=True),
    sa.Column('dropbacks', sa.Float(), nullable=True),
    sa.Column('epa', sa.Float(), nullable=True),
    sa.Column('successes', sa.Float(), nullable=True),
    sa.Column('yards', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('team_id', 'game_id', 'grouping')
    )
    op.create_index(op.f('ix_team_personnel_season'), 'team_personnel', ['season'], unique=False)
    op.add_column('teams', sa.Column('color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###
    for table in NEW_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        for role in ("anon", "authenticated"):
            op.execute(
                f"DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{role}') "
                f"THEN REVOKE ALL ON TABLE {table} FROM {role}; END IF; END $$;"
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'color')
    op.drop_index(op.f('ix_team_personnel_season'), table_name='team_personnel')
    op.drop_table('team_personnel')
    op.drop_index('ix_team_game_stats_season', table_name='team_game_stats')
    op.drop_table('team_game_stats')
    op.drop_table('team_staff')
    # ### end Alembic commands ###
