"""Explore: play_targets and player_run_lanes

Two tables for the Explore tab. ``play_targets`` holds one row per targeted pass (who
threw it, who it was for, depth, side, result), which the passing network, the target
heatmaps and the air-yard distributions aggregate for any weeks a request asks for.
``player_run_lanes`` holds each player's designed runs per game and run lane, with how
they ended, for the running back comparison charts.

Both are RLS-locked in this migration, like every table in ``public`` (CLAUDE.md), and
``anon`` / ``authenticated`` lose their default grants on them.

Revision ID: 311908bb9b96
Revises: 177a7137df5c
Create Date: 2026-09-28 21:48:33.909019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311908bb9b96'
down_revision: Union[str, None] = '177a7137df5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NEW_TABLES = ("play_targets", "player_run_lanes")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('play_targets',
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('play_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('season_type', sa.String(length=20), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('passer_id', sa.String(length=50), nullable=True),
    sa.Column('receiver_id', sa.String(length=50), nullable=True),
    sa.Column('air_yards', sa.SmallInteger(), nullable=True),
    sa.Column('location', sa.String(length=6), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('touchdown', sa.Boolean(), nullable=False),
    sa.Column('interception', sa.Boolean(), nullable=False),
    sa.Column('first_down', sa.Boolean(), nullable=False),
    sa.Column('yards', sa.SmallInteger(), nullable=False),
    sa.Column('yards_after_catch', sa.SmallInteger(), nullable=True),
    sa.Column('epa', sa.Float(), nullable=True),
    sa.Column('down', sa.SmallInteger(), nullable=True),
    sa.Column('yardline_100', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'play_id')
    )
    op.create_index('ix_play_targets_season_passer', 'play_targets', ['season', 'passer_id'], unique=False)
    op.create_index('ix_play_targets_season_receiver', 'play_targets', ['season', 'receiver_id'], unique=False)
    op.create_index('ix_play_targets_season_team', 'play_targets', ['season', 'team_id'], unique=False)
    op.create_table('player_run_lanes',
    sa.Column('player_id', sa.String(length=50), nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('lane', sa.String(length=8), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('season_type', sa.String(length=20), nullable=False),
    sa.Column('carries', sa.Integer(), nullable=False),
    sa.Column('yards', sa.Integer(), nullable=False),
    sa.Column('successes', sa.Integer(), nullable=False),
    sa.Column('first_downs', sa.Integer(), nullable=False),
    sa.Column('touchdowns', sa.Integer(), nullable=False),
    sa.Column('stuffed', sa.Integer(), nullable=False),
    sa.Column('short', sa.Integer(), nullable=False),
    sa.Column('medium', sa.Integer(), nullable=False),
    sa.Column('explosive', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'game_id', 'lane')
    )
    op.create_index('ix_player_run_lanes_player_season', 'player_run_lanes', ['player_id', 'season'], unique=False)
    # ### end Alembic commands ###
    for table in NEW_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        for role in ("anon", "authenticated"):
            op.execute(
                f"DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{role}') "
                f"THEN REVOKE ALL ON TABLE {table} FROM {role}; END IF; END $$;"
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_player_run_lanes_player_season', table_name='player_run_lanes')
    op.drop_table('player_run_lanes')
    op.drop_index('ix_play_targets_season_team', table_name='play_targets')
    op.drop_index('ix_play_targets_season_receiver', table_name='play_targets')
    op.drop_index('ix_play_targets_season_passer', table_name='play_targets')
    op.drop_table('play_targets')
    # ### end Alembic commands ###
