"""M6.1: player_rankings table

Consensus expert rankings (FantasyPros ECR via `load_ff_rankings`), the market half of
the Draft Value Board.

Named for what it holds. The roadmap planned a `projections` table here; the feed turned
out to publish **ranks, not projections** — ECR with its dispersion, no projected points
and no ADP. That distinction is load-bearing in this product: a projection is stat
components the M1 engine can rescore into any league, while a rank is an opinion already
frozen in someone else's scoring. So `projections` stays unbuilt until there is a real
projection source, and this table carries `source` + `ranking_type` so a second provider
is additive (the multi-source spine in docs/ROADMAP.md).

`scraped_at` is in the primary key because the upstream file is a *snapshot* overwritten
in place, not a time series — history only accrues from our first ingest. `week` is 0 for
a draft ranking rather than NULL, since a primary-key column cannot be NULL.

No RLS: this is public reference data, the documented exemption from the rule that
user-data tables must lock PostgREST out (see 8f73b5b2b1a1).

Revision ID: 319f1f54a7f0
Revises: 7fa8428b7a1d
Create Date: 2026-08-20 21:27:03.415207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319f1f54a7f0'
down_revision: Union[str, None] = '7fa8428b7a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_rankings',
    sa.Column('player_id', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('ranking_type', sa.String(length=40), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('scraped_at', sa.Date(), nullable=False),
    sa.Column('ecr', sa.Float(), nullable=True),
    sa.Column('sd', sa.Float(), nullable=True),
    sa.Column('best', sa.Integer(), nullable=True),
    sa.Column('worst', sa.Integer(), nullable=True),
    sa.Column('rank_delta', sa.Float(), nullable=True),
    sa.Column('player_owned_avg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'source', 'ranking_type', 'season', 'week', 'scraped_at')
    )
    op.create_index('ix_rankings_lookup', 'player_rankings', ['source', 'ranking_type', 'season', 'week', 'scraped_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rankings_lookup', table_name='player_rankings')
    op.drop_table('player_rankings')
    # ### end Alembic commands ###
