"""unique constraint on team abbreviation

Revision ID: 4a2fb3bf6c6b
Revises: bd93cb7cea4b
Create Date: 2026-07-14 19:50:43.677763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a2fb3bf6c6b'
down_revision: Union[str, None] = 'bd93cb7cea4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_teams_abbreviation', table_name='teams')
    op.create_index(op.f('ix_teams_abbreviation'), 'teams', ['abbreviation'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_abbreviation'), table_name='teams')
    op.create_index('ix_teams_abbreviation', 'teams', ['abbreviation'], unique=False)
    # ### end Alembic commands ###
