"""M2 expanded metrics: expected components, market share, inside-yardline rushes

Revision ID: 521f727f5461
Revises: 4a2fb3bf6c6b
Create Date: 2026-07-29 19:30:14.792281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '521f727f5461'
down_revision: Union[str, None] = '4a2fb3bf6c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_stats', sa.Column('rush_att_inside_10', sa.Integer(), nullable=True))
    op.add_column('player_stats', sa.Column('rush_att_inside_5', sa.Integer(), nullable=True))
    op.add_column('player_stats', sa.Column('rush_att_inside_2', sa.Integer(), nullable=True))
    op.add_column('player_stats', sa.Column('rush_attempt_share', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('opportunity_share', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('market_share', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('passing_yards_exp', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('passing_tds_exp', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('interceptions_exp', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('rushing_yards_exp', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('rushing_tds_exp', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('receiving_yards_exp', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('receiving_tds_exp', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('receptions_exp', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('two_point_conv_exp', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_stats', 'two_point_conv_exp')
    op.drop_column('player_stats', 'receptions_exp')
    op.drop_column('player_stats', 'receiving_tds_exp')
    op.drop_column('player_stats', 'receiving_yards_exp')
    op.drop_column('player_stats', 'rushing_tds_exp')
    op.drop_column('player_stats', 'rushing_yards_exp')
    op.drop_column('player_stats', 'interceptions_exp')
    op.drop_column('player_stats', 'passing_tds_exp')
    op.drop_column('player_stats', 'passing_yards_exp')
    op.drop_column('player_stats', 'market_share')
    op.drop_column('player_stats', 'opportunity_share')
    op.drop_column('player_stats', 'rush_attempt_share')
    op.drop_column('player_stats', 'rush_att_inside_2')
    op.drop_column('player_stats', 'rush_att_inside_5')
    op.drop_column('player_stats', 'rush_att_inside_10')
    # ### end Alembic commands ###
