"""M4: player_target_depth table

Revision ID: 7852e5b550b0
Revises: 521f727f5461
Create Date: 2026-07-30 20:00:08.691449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7852e5b550b0'
down_revision: Union[str, None] = '521f727f5461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_target_depth',
    sa.Column('player_id', sa.String(length=50), nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('depth_bucket', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('season_type', sa.String(length=20), nullable=True),
    sa.Column('targets', sa.Integer(), nullable=True),
    sa.Column('receptions', sa.Integer(), nullable=True),
    sa.Column('receiving_yards', sa.Integer(), nullable=True),
    sa.Column('receiving_tds', sa.Integer(), nullable=True),
    sa.Column('air_yards', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'game_id', 'depth_bucket', 'direction')
    )
    op.create_index('ix_target_depth_player_season', 'player_target_depth', ['player_id', 'season'], unique=False)
    op.create_index('ix_target_depth_season_week', 'player_target_depth', ['season', 'week'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_target_depth_season_week', table_name='player_target_depth')
    op.drop_index('ix_target_depth_player_season', table_name='player_target_depth')
    op.drop_table('player_target_depth')
    # ### end Alembic commands ###
