"""M6.0: season readiness - vegas lines on games, bio columns on players

Two additions, both to columns nflverse has been publishing all along and the
pipeline was discarding.

**games** gains the betting market's view of each game. These arrive in the same
`load_schedules` feed the table is already built from, populated for finished games
(closing lines) *and* for upcoming ones — which is why the M6 Vegas board needs no
external odds API. Implied team totals are derived at query time from `spread_line`
and `total_line`, not stored. `roof` / `surface` / `div_game` come along as game
context a fantasy question actually asks about (dome games, turf, division rivalry).

**players** gains the roster-bio columns: `load_players` publishes 39 columns and
this table stored 7. Age and draft capital are draft-board inputs, not trivia, and
the M6 Draft Value Board needs them. `draft_team` is a bare abbreviation, not a
foreign key — it can name a franchise that no longer exists under that code (OAK,
SD, STL) while `teams` holds today's 32.

No RLS here: both are NFL reference tables holding public, read-only facts, which is
the documented exemption from the rule that user-data tables must lock PostgREST out
(see migration 8f73b5b2b1a1).

Revision ID: 7fa8428b7a1d
Revises: 8f73b5b2b1a1
Create Date: 2026-08-20 13:07:46.982418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa8428b7a1d'
down_revision: Union[str, None] = '8f73b5b2b1a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('spread_line', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('total_line', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('home_moneyline', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_moneyline', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('over_odds', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('under_odds', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('roof', sa.String(length=20), nullable=True))
    op.add_column('games', sa.Column('surface', sa.String(length=20), nullable=True))
    op.add_column('games', sa.Column('div_game', sa.Boolean(), nullable=True))
    op.add_column('players', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('players', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('college_name', sa.String(length=100), nullable=True))
    op.add_column('players', sa.Column('college_conference', sa.String(length=100), nullable=True))
    op.add_column('players', sa.Column('draft_year', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('draft_round', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('draft_pick', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('draft_team', sa.String(length=10), nullable=True))
    op.add_column('players', sa.Column('rookie_season', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('years_of_experience', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'years_of_experience')
    op.drop_column('players', 'rookie_season')
    op.drop_column('players', 'draft_team')
    op.drop_column('players', 'draft_pick')
    op.drop_column('players', 'draft_round')
    op.drop_column('players', 'draft_year')
    op.drop_column('players', 'college_conference')
    op.drop_column('players', 'college_name')
    op.drop_column('players', 'weight')
    op.drop_column('players', 'height')
    op.drop_column('players', 'birth_date')
    op.drop_column('games', 'div_game')
    op.drop_column('games', 'surface')
    op.drop_column('games', 'roof')
    op.drop_column('games', 'under_odds')
    op.drop_column('games', 'over_odds')
    op.drop_column('games', 'away_moneyline')
    op.drop_column('games', 'home_moneyline')
    op.drop_column('games', 'total_line')
    op.drop_column('games', 'spread_line')
    # ### end Alembic commands ###
