"""M5 accounts: users, league_profiles, favorites, saved_views

The four tables M5 adds. `users` mirrors the Supabase Auth subject so the other
three have a real foreign key to hang off; everything cascades from it, which is
what makes account deletion a five-line handler.

See docs/design/M5-accounts-saved-state.md.

Revision ID: 990003c7c7cf
Revises: 7852e5b550b0
Create Date: 2026-08-04 21:15:54.591483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990003c7c7cf'
down_revision: Union[str, None] = '7852e5b550b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('league_profiles',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('scoring_spec', sa.String(length=500), nullable=False),
    sa.Column('league_spec', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_profile_user_name')
    )
    op.create_index(op.f('ix_league_profiles_user_id'), 'league_profiles', ['user_id'], unique=False)
    # At most one active profile per user, enforced by the database rather than by
    # application logic alone. Partial index: rows with is_active = false are exempt.
    op.create_index(
        'uq_profile_one_active', 'league_profiles', ['user_id'],
        unique=True, postgresql_where=sa.text('is_active'),
    )
    op.create_table('saved_views',
    sa.Column('view_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('path', sa.String(length=120), nullable=False),
    sa.Column('query', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('view_id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_view_user_name')
    )
    op.create_index(op.f('ix_saved_views_user_id'), 'saved_views', ['user_id'], unique=False)
    op.create_table('favorites',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_index(op.f('ix_saved_views_user_id'), table_name='saved_views')
    op.drop_table('saved_views')
    op.drop_index('uq_profile_one_active', table_name='league_profiles')
    op.drop_index(op.f('ix_league_profiles_user_id'), table_name='league_profiles')
    op.drop_table('league_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
