"""M6.2: depth_chart_entries table

Where each skill-position player currently sits on their team's depth chart, and the
home of the M6.2 team pages.

**Current state, not history.** The upstream feed publishes timestamped snapshots — 152
of them for the 2026 season by mid-August, ~450k rows a season — and this table keeps
one row per player from the newest. That is a reversible choice: nflverse retains every
snapshot, so a change-log ("promoted to WR2 on Aug 12") can be backfilled from the same
feed if it ever earns its place.

The consequence lives in the pipeline rather than here: because the table holds current
state, the ingest replaces each team's rows in a transaction instead of upserting. A cut
player stops appearing in the feed, so an upsert alone would leave him on the chart
forever.

QB/RB/WR/TE only, matching project scope. No RLS: public reference data, the documented
exemption (see 8f73b5b2b1a1).

Revision ID: a6763fb36779
Revises: 319f1f54a7f0
Create Date: 2026-08-20 21:43:19.168120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6763fb36779'
down_revision: Union[str, None] = '319f1f54a7f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depth_chart_entries',
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=50), nullable=False),
    sa.Column('pos_abb', sa.String(length=5), nullable=False),
    sa.Column('pos_rank', sa.Integer(), nullable=True),
    sa.Column('pos_slot', sa.Integer(), nullable=True),
    sa.Column('pos_grp', sa.String(length=30), nullable=True),
    sa.Column('pos_name', sa.String(length=50), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('season', 'team_id', 'player_id', 'pos_abb')
    )
    op.create_index('ix_depth_chart_team', 'depth_chart_entries', ['team_id', 'season', 'pos_abb', 'pos_rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_depth_chart_team', table_name='depth_chart_entries')
    op.drop_table('depth_chart_entries')
    # ### end Alembic commands ###
