"""create core tables

Revision ID: bd93cb7cea4b
Revises: 
Create Date: 2026-07-14 19:32:38.424886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd93cb7cea4b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('abbreviation', sa.String(length=5), nullable=True),
    sa.Column('conference', sa.String(length=10), nullable=True),
    sa.Column('division', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index(op.f('ix_teams_abbreviation'), 'teams', ['abbreviation'], unique=False)
    op.create_table('games',
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('season_type', sa.String(length=20), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('game_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index(op.f('ix_games_season'), 'games', ['season'], unique=False)
    op.create_index(op.f('ix_games_week'), 'games', ['week'], unique=False)
    op.create_table('players',
    sa.Column('player_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=5), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('headshot_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_index(op.f('ix_players_position'), 'players', ['position'], unique=False)
    op.create_table('player_stats',
    sa.Column('stat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(length=50), nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('season_type', sa.String(length=20), nullable=True),
    sa.Column('passing_yards', sa.Integer(), nullable=True),
    sa.Column('passing_tds', sa.Integer(), nullable=True),
    sa.Column('interceptions', sa.Integer(), nullable=True),
    sa.Column('completions', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('rushing_yards', sa.Integer(), nullable=True),
    sa.Column('rushing_tds', sa.Integer(), nullable=True),
    sa.Column('carries', sa.Integer(), nullable=True),
    sa.Column('receiving_yards', sa.Integer(), nullable=True),
    sa.Column('receiving_tds', sa.Integer(), nullable=True),
    sa.Column('receptions', sa.Integer(), nullable=True),
    sa.Column('targets', sa.Integer(), nullable=True),
    sa.Column('fumbles', sa.Integer(), nullable=True),
    sa.Column('fumbles_lost', sa.Integer(), nullable=True),
    sa.Column('epa', sa.Float(), nullable=True),
    sa.Column('cpoe', sa.Float(), nullable=True),
    sa.Column('air_yards', sa.Float(), nullable=True),
    sa.Column('air_yards_share', sa.Float(), nullable=True),
    sa.Column('target_share', sa.Float(), nullable=True),
    sa.Column('racr', sa.Float(), nullable=True),
    sa.Column('wopr', sa.Float(), nullable=True),
    sa.Column('snap_count', sa.Integer(), nullable=True),
    sa.Column('snap_share', sa.Float(), nullable=True),
    sa.Column('yards_after_catch', sa.Float(), nullable=True),
    sa.Column('adot', sa.Float(), nullable=True),
    sa.Column('passer_rating', sa.Float(), nullable=True),
    sa.Column('rushing_epa', sa.Float(), nullable=True),
    sa.Column('receiving_epa', sa.Float(), nullable=True),
    sa.Column('red_zone_rush_share', sa.Float(), nullable=True),
    sa.Column('red_zone_rush_attempts', sa.Integer(), nullable=True),
    sa.Column('red_zone_targets', sa.Integer(), nullable=True),
    sa.Column('targets_per_route_run', sa.Float(), nullable=True),
    sa.Column('slot_snaps', sa.Integer(), nullable=True),
    sa.Column('routes_run', sa.Integer(), nullable=True),
    sa.Column('route_participation', sa.Float(), nullable=True),
    sa.Column('unrealized_air_yards', sa.Float(), nullable=True),
    sa.Column('yards_per_route_run', sa.Float(), nullable=True),
    sa.Column('yards_per_target', sa.Float(), nullable=True),
    sa.Column('yards_per_reception', sa.Float(), nullable=True),
    sa.Column('fantasy_points_ppr', sa.Float(), nullable=True),
    sa.Column('fantasy_points_half', sa.Float(), nullable=True),
    sa.Column('fantasy_points_std', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('stat_id'),
    sa.UniqueConstraint('player_id', 'game_id', name='uq_player_game')
    )
    op.create_index(op.f('ix_player_stats_game_id'), 'player_stats', ['game_id'], unique=False)
    op.create_index(op.f('ix_player_stats_player_id'), 'player_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_stats_season'), 'player_stats', ['season'], unique=False)
    op.create_index(op.f('ix_player_stats_week'), 'player_stats', ['week'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_stats_week'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_season'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_player_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_game_id'), table_name='player_stats')
    op.drop_table('player_stats')
    op.drop_index(op.f('ix_players_position'), table_name='players')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_games_week'), table_name='games')
    op.drop_index(op.f('ix_games_season'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_teams_abbreviation'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
